version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=contact-list-db
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - ':3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contact-list-db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
